### ISSUE TITLE
resize window on empty grid cause exception

### ISSUE THREAD

**Issue by cjkao** [cjkao/slickdart#65]
Uncaught Unhandled exception:
The null object does not have a getter 'previousNode'.

NoSuchMethodError: method not found: 'previousNode'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      SlickGrid.ensureCellNodesInRowsCache (package:slickdart/slick_grid.dart:2450:35)
#3      SlickGrid._cleanUpAndRenderCells._helper (package:slickdart/slick_grid.dart:2370:13)
#4      SlickGrid._cleanUpAndRenderCells (package:slickdart/slick_grid.dart:2404:16)
#5      SlickGrid.render (package:slickdart/slick_grid.dart:558:7)
#6      SlickGrid.resizeCanvas (package:slickdart/slick_grid.dart:795:5)

**Comment by cjkao** [comment]
wrapper issue
